version: "2"

services:
  plex_main:
    image: plexinc/pms-docker:latest 
    restart: unless-stopped  
    networks:
      - plexnet
    ports:
      - "32400:32400"
      - "3005:3005"
      - "8324:8324"
      - "32469:32469"
      - "1900:1900"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"   
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - HOSTNAME=plextest1
      - ADVERTISE_IP=http://10.7.0.52:32400/
    volumes:
      - config_data_p1:/config
      - trans_data:/transcode
      - c:/users/dboehm/videos/:/data
  
  plex_dizquetv:
    image: plexinc/pms-docker:latest 
    restart: unless-stopped  
    networks:
      - plexnet
    ports:
      - "32401:32400"      
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - HOSTNAME=plextest2
      - ADVERTISE_IP=http://10.7.0.52:32401/
    volumes:
      - config_data_p2:/config
      - trans_data:/transcode
      - c:/users/dboehm/videos/:/data

  dizquetv:   
    image: vexorian/dizquetv:latest   
    restart: unless-stopped 
    networks:
      - plexnet
    ports:
      - "8001:8000"
    volumes:
      - ./.dizquetv:/home/node/app/.dizquetv
    

networks:
  plexnet:
volumes:
  config_data_p1:
  config_data_p2:
  trans_data:    